# Generated by Django 5.2 on 2025-07-11 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICourseBuilderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Publishing'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_objectives', models.JSONField(blank=True, default=list, null=True)),
                ('target_audience', models.JSONField(blank=True, default=list, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outline', models.JSONField(blank=True, default=dict, null=True)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('assessments', models.JSONField(blank=True, default=dict, null=True)),
                ('has_outline', models.BooleanField(default=False)),
                ('has_modules', models.BooleanField(default=False)),
                ('has_lessons', models.BooleanField(default=False)),
                ('has_assessments', models.BooleanField(default=False)),
                ('generation_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_course_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Course Builder Draft',
                'verbose_name_plural': 'AI Course Builder Drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
