# Generated by Django 5.2 on 2025-06-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_course_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aicoursebuilderdraft',
            old_name='duration_seconds',
            new_name='duration_minutes',
        ),
    ]
