# Generated by Django 5.2 on 2025-06-15 16:30

import courses.models
import courses.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('answer_text', models.CharField(help_text='Answer text (minimum 1 character)', max_length=500, validators=[courses.validators.MinStrLenValidator(1)])),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for this answer choice', null=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Assessment title (minimum 2 characters)', max_length=255, validators=[courses.validators.MinStrLenValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Assessment description or instructions', null=True)),
                ('time_limit', models.PositiveIntegerField(default=0, help_text='Time limit in minutes, 0 means no limit')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Passing score percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), courses.validators.validate_percentage])),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomize question order for each attempt')),
                ('show_results', models.BooleanField(default=True, help_text='Show results immediately after completion')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('title', models.CharField(help_text='Lesson title (minimum 2 characters)', max_length=255, validators=[courses.validators.MinStrLenValidator(2)])),
                ('content', models.TextField(help_text='Full content visible to authorized users (minimum 10 characters)', validators=[courses.validators.MinStrLenValidator(10)])),
                ('guest_content', models.TextField(blank=True, help_text='Preview content for unregistered users', null=True)),
                ('registered_content', models.TextField(blank=True, help_text='Limited content for registered users', null=True)),
                ('access_level', models.CharField(choices=[('guest', 'Guest - Unregistered Users'), ('registered', 'Registered - Logged In Users'), ('premium', 'Premium - Paid Subscribers')], default='registered', help_text='Minimum access level required to view this lesson', max_length=20)),
                ('type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('lab_exercise', 'Lab Exercise'), ('assignment', 'Assignment'), ('discussion', 'Discussion')], default='video', help_text='Type of lesson content', max_length=20)),
                ('has_assessment', models.BooleanField(default=False, help_text='Whether lesson includes an assessment')),
                ('has_lab', models.BooleanField(default=False, help_text='Whether lesson includes a lab exercise')),
                ('is_free_preview', models.BooleanField(default=False, help_text='Whether lesson is available as free preview')),
                ('video_url', models.URLField(blank=True, help_text='URL for video content', null=True, validators=[courses.validators.validate_video_url])),
                ('transcript', models.TextField(blank=True, help_text='Video transcript or lesson transcript', null=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When attempt was started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When attempt was completed', null=True)),
                ('score', models.PositiveIntegerField(default=0, help_text='Raw score achieved')),
                ('passed', models.BooleanField(default=False, help_text='Whether attempt passed the assessment')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt number for this user/assessment combination')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user during attempt', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string during attempt', null=True)),
                ('assessment', models.ForeignKey(help_text='Assessment being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.assessment')),
                ('user', models.ForeignKey(help_text='User taking the assessment', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Category name (minimum 2 characters)', max_length=100, unique=True, validators=[courses.validators.MinStrLenValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for display')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_date'], name='courses_cat_created_8cf2cb_idx'), models.Index(fields=['updated_date'], name='courses_cat_updated_67ffb8_idx'), models.Index(fields=['slug'], name='courses_cat_slug_33564e_idx'), models.Index(fields=['is_active'], name='courses_cat_is_acti_61a38c_idx'), models.Index(fields=['sort_order'], name='courses_cat_sort_or_896e38_idx'), models.Index(fields=['name'], name='courses_cat_name_ab7c10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Course title (minimum 3 characters)', max_length=160, validators=[courses.validators.MinStrLenValidator(3)])),
                ('subtitle', models.CharField(blank=True, help_text='Optional course subtitle', max_length=255, null=True)),
                ('description', models.TextField(help_text='Course description (minimum 50 characters)', validators=[courses.validators.MinStrLenValidator(50)])),
                ('thumbnail', models.ImageField(blank=True, help_text='Course thumbnail', null=True, upload_to='course_thumbnails/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('490.0'), help_text='Course price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0), courses.validators.validate_price_range])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), courses.validators.validate_price_range])),
                ('discount_ends', models.DateTimeField(blank=True, help_text='Discount expiration date', null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', help_text='Course difficulty level', max_length=20)),
                ('duration', models.CharField(blank=True, help_text='Legacy field for display', max_length=100, null=True)),
                ('has_certificate', models.BooleanField(default=False, help_text='Whether course offers completion certificate')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether course is featured on homepage')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of course requirements', validators=[courses.validators.JSONListValidator(max_items=20, min_str_len=3)])),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills students will learn', validators=[courses.validators.JSONListValidator(max_items=15, min_str_len=2)])),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives', validators=[courses.validators.JSONListValidator(max_items=15, min_str_len=5)])),
                ('target_audience', models.TextField(blank=True, help_text='Description of target audience', null=True)),
                ('creation_method', models.CharField(choices=[('builder', 'Drag & Drop Builder'), ('wizard', 'Step-by-Step Wizard'), ('ai', 'AI-Powered Builder'), ('import', 'Imported Course'), ('manual', 'Manual Creation')], default='builder', help_text='Method used to create course', max_length=20)),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('partially_complete', 'Partially Complete'), ('complete', 'Complete'), ('published', 'Published'), ('archived', 'Archived')], default='not_started', help_text='Course completion status', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0, help_text='Completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), courses.validators.validate_percentage])),
                ('version', models.FloatField(default=1.0, help_text='Course version number')),
                ('is_draft', models.BooleanField(default=True, help_text='Whether course is in draft state')),
                ('enrolled_students_count', models.PositiveIntegerField(default=0, help_text='Cached count of enrolled students')),
                ('avg_rating', models.FloatField(default=0.0, help_text='Average rating from reviews')),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Total number of reviews')),
                ('last_enrollment_date', models.DateTimeField(blank=True, help_text='Date of last student enrollment', null=True)),
                ('category', models.ForeignKey(default=courses.models.get_default_category, help_text='Course category', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Parent course version for cloned courses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_date'],
                'abstract': False,
            },
            bases=(models.Model, courses.models.AnalyticsCourseMixin),
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Instructor title or role', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Instructor bio for this course', null=True)),
                ('is_lead', models.BooleanField(default=False, help_text='Whether this instructor is the lead instructor')),
                ('course', models.ForeignKey(help_text='Associated course', on_delete=django.db.models.deletion.CASCADE, related_name='courseinstructor_set', to='courses.course')),
                ('instructor', models.ForeignKey(help_text='Instructor user', on_delete=django.db.models.deletion.CASCADE, related_name='course_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended'), ('unenrolled', 'Unenrolled')], default='active', help_text='Enrollment status', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when course was completed', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time student accessed the course')),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in seconds')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), courses.validators.validate_percentage])),
                ('course', models.ForeignKey(help_text='Enrolled course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('last_lesson_accessed', models.ForeignKey(blank=True, help_text='Last lesson accessed by student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_enrollments', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(help_text='Unique certificate number', max_length=50, unique=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether certificate is valid')),
                ('revocation_date', models.DateTimeField(blank=True, help_text='Date when certificate was revoked', null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for certificate revocation', null=True)),
                ('verification_hash', models.CharField(blank=True, help_text='SHA-256 hash for verification', max_length=64, unique=True)),
                ('template_version', models.CharField(default='1.0', help_text='Certificate template version', max_length=10)),
                ('enrollment', models.OneToOneField(help_text='Associated enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='lesson',
            field=models.OneToOneField(help_text='Associated lesson', on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='courses.lesson'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Module title (minimum 2 characters)', max_length=255, validators=[courses.validators.MinStrLenValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Module description', null=True)),
                ('course', models.ForeignKey(help_text='Parent course', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(help_text='Parent module', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Note content', validators=[courses.validators.MinStrLenValidator(1)])),
                ('is_private', models.BooleanField(default=True, help_text='Whether this note is private to the user')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organizing notes', validators=[courses.validators.JSONListValidator(max_items=10, min_str_len=2)])),
                ('lesson', models.ForeignKey(help_text='Lesson the note is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson')),
                ('user', models.ForeignKey(help_text='User who created the note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether lesson is completed')),
                ('completed_date', models.DateTimeField(blank=True, help_text='Date when lesson was completed', null=True)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent on this lesson in seconds')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress within this specific lesson (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), courses.validators.validate_percentage])),
                ('notes', models.TextField(blank=True, help_text='Student notes for this lesson', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time lesson was accessed')),
                ('enrollment', models.ForeignKey(help_text='Associated enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress Records',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField(help_text='Question text (minimum 5 characters)', validators=[courses.validators.MinStrLenValidator(5)])),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank')], help_text='Type of question', max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer', validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering', null=True)),
                ('assessment', models.ForeignKey(help_text='Parent assessment', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.assessment')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for open-ended questions', null=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned for this answer')),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback for this answer', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When answer was submitted')),
                ('attempt', models.ForeignKey(help_text='Associated assessment attempt', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.assessmentattempt')),
                ('selected_answer', models.ForeignKey(blank=True, help_text='Selected answer for multiple choice questions', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.answer')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Parent question', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('storage_key', models.CharField(blank=True, help_text='Cloud storage path/object name', max_length=512, null=True)),
                ('uploaded', models.BooleanField(default=False, help_text='Whether file uploaded successfully')),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of uploaded file', max_length=120, null=True)),
                ('title', models.CharField(help_text='Resource title (minimum 2 characters)', max_length=255, validators=[courses.validators.MinStrLenValidator(2)])),
                ('type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Link'), ('code_sample', 'Code Sample'), ('tool/software', 'Tool/Software'), ('dataset', 'Dataset'), ('template', 'Template')], help_text='Type of resource', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Resource description', null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded file resource', null=True, upload_to='lesson_resources/')),
                ('url', models.URLField(blank=True, help_text='External URL resource', null=True)),
                ('premium', models.BooleanField(default=False, help_text='Whether this resource requires premium subscription')),
                ('lesson', models.ForeignKey(help_text='Parent lesson', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=255, null=True)),
                ('content', models.TextField(help_text='Review content (minimum 10 characters)', validators=[courses.validators.MinStrLenValidator(10)])),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether reviewer is enrolled in the course')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether review is approved for display')),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal moderation notes', null=True)),
                ('course', models.ForeignKey(help_text='Course being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['created_date'], name='courses_ass_created_1b844b_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['updated_date'], name='courses_ass_updated_a99f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'assessment'], name='courses_ass_user_id_fedd97_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assessment', '-start_time'], name='courses_ass_assessm_ba39be_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['passed'], name='courses_ass_passed_2bf6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['attempt_number'], name='courses_ass_attempt_d56abe_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_date'], name='courses_cou_created_7da7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['updated_date'], name='courses_cou_updated_517180_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='courses_cou_is_publ_4b99b9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['published_date'], name='courses_cou_publish_80f4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['view_count'], name='courses_cou_view_co_55d4de_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['last_accessed'], name='courses_cou_last_ac_9655a6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_published'], name='courses_cou_categor_e9e0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured', 'is_published'], name='courses_cou_is_feat_6821f1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'is_published'], name='courses_cou_level_a2b259_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['parent_version', 'version'], name='courses_cou_parent__886ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['creation_method'], name='courses_cou_creatio_6175b0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['completion_status'], name='courses_cou_complet_a28d16_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_draft'], name='courses_cou_is_draf_460a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['created_date'], name='courses_cou_created_5f4df7_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['updated_date'], name='courses_cou_updated_61fbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_d38778_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['course', 'is_active'], name='courses_cou_course__a0cdd8_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['instructor', 'is_active'], name='courses_cou_instruc_9ffb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseinstructor',
            index=models.Index(fields=['is_lead'], name='courses_cou_is_lead_7093a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstructor',
            unique_together={('course', 'instructor')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['created_date'], name='courses_cer_created_6482f3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['updated_date'], name='courses_cer_updated_e6b0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='courses_cer_certifi_b5881b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_hash'], name='courses_cer_verific_19df54_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_valid'], name='courses_cer_is_vali_2f2340_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['revocation_date'], name='courses_cer_revocat_79b12c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['created_date'], name='courses_enr_created_2cb035_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['updated_date'], name='courses_enr_updated_05225a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='courses_enr_user_id_ce8b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='courses_enr_status_4fd017_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['completion_date'], name='courses_enr_complet_57338c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['progress_percentage'], name='courses_enr_progres_dba947_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['created_date'], name='courses_ass_created_110f50_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['updated_date'], name='courses_ass_updated_f528d4_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['lesson'], name='courses_ass_lesson__4afa06_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['passing_score'], name='courses_ass_passing_b8a83e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['created_date'], name='courses_mod_created_9a6a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['updated_date'], name='courses_mod_updated_141b50_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order'], name='courses_mod_order_e9c068_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published'], name='courses_mod_is_publ_875329_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['published_date'], name='courses_mod_publish_823717_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='courses_mod_course__20183c_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'is_published'], name='courses_mod_course__92d7f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_date'], name='courses_les_created_7fbce2_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['updated_date'], name='courses_les_updated_ac21ad_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order'], name='courses_les_order_ffd43c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='courses_les_module__4accd4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['access_level'], name='courses_les_access__657329_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['type'], name='courses_les_type_805272_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_free_preview'], name='courses_les_is_free_a8e681_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['has_assessment'], name='courses_les_has_ass_d9b62a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['has_lab'], name='courses_les_has_lab_01b267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_date'], name='courses_not_created_9af681_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['updated_date'], name='courses_not_updated_de721c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'lesson'], name='courses_not_user_id_eece44_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['lesson', 'is_private'], name='courses_not_lesson__5f16a2_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_private'], name='courses_not_is_priv_3def52_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['created_date'], name='courses_pro_created_6822b9_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['updated_date'], name='courses_pro_updated_f54b15_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_pro_enrollm_e8bb03_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['lesson', 'is_completed'], name='courses_pro_lesson__76321e_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['completed_date'], name='courses_pro_complet_5ebc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['progress_percentage'], name='courses_pro_progres_c67c74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_date'], name='courses_que_created_c1161f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['updated_date'], name='courses_que_updated_019a24_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='courses_que_order_cede08_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assessment', 'order'], name='courses_que_assessm_2927ae_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='courses_que_questio_beffac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['points'], name='courses_que_points_6da46d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('assessment', 'order')},
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'question'], name='courses_att_attempt_aab6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['is_correct'], name='courses_att_is_corr_be0997_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['answered_at'], name='courses_att_answere_e6edf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_date'], name='courses_ans_created_cd6cee_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['updated_date'], name='courses_ans_updated_64a917_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['order'], name='courses_ans_order_fc4c07_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'order'], name='courses_ans_questio_aedf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='courses_ans_is_corr_9dd4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_date'], name='courses_res_created_2d1e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['updated_date'], name='courses_res_updated_5e9c80_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['order'], name='courses_res_order_e289a6_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploaded'], name='courses_res_uploade_42c1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['mime_type'], name='courses_res_mime_ty_616554_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['lesson', 'order'], name='courses_res_lesson__12dbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['type'], name='courses_res_type_380823_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['premium'], name='courses_res_premium_945503_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_date'], name='courses_rev_created_128172_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['updated_date'], name='courses_rev_updated_dc0b78_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', '-created_date'], name='courses_rev_course__c5c65a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='courses_rev_rating_004eae_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='courses_rev_is_appr_003b67_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase'], name='courses_rev_is_veri_6e432c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'course')},
        ),
    ]
