# Generated by Django 5.2 on 2025-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_convert_enums_to_textchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='completion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('partially_complete', 'Partially Complete'), ('complete', 'Complete'), ('published', 'Published'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='not_started', help_text='Course completion status', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', help_text='Course difficulty level', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended'), ('unenrolled', 'Unenrolled'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', help_text='Enrollment status', max_length=20),
        ),
    ]
