# Generated by Django 5.2 on 2025-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='login_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
