# Generated by Django 5.2 on 2025-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('guest', 'Guest'), ('registered', 'Registered'), ('premium', 'Premium')], default='registered', max_length=20),
        ),
    ]
