# Generated by Django 5.2 on 2025-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscription_tier'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='users_email_token_c80ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'is_used'], name='users_email_user_id_8f79bf_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', 'timestamp'], name='users_login_user_id_312dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='users_login_ip_addr_651077_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['token'], name='users_passw_token_2def9c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['user', 'is_used'], name='users_passw_user_id_61b761_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='users_users_session_70af4d_idx'),
        ),
    ]
