#!/usr/bin/env python3

from setuptools import setup, find_packages
import os

# Read version from __init__.py
with open(os.path.join('backend_analyzer', '__init__.py'), 'r') as f:
    for line in f:
        if line.startswith('__version__'):
            version = line.split('=')[1].strip().strip('"\'')
            break
    else:
        version = '0.1.0'

# Read long description from README
with open('README.md', 'r', encoding='utf-8') as f:
    long_description = f.read()

setup(
    name="django-backend-analyzer",
    version=version,
    description="Tool for analyzing Django backend codebases to facilitate frontend integration",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Generated by GitHub Copilot",
    author_email="info@example.com",
    url="https://github.com/example/django-backend-analyzer",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "colorama>=0.4.4",
        "toml>=0.10.2",
        "pyyaml>=6.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.3.0",
            "isort>=5.10.1",
            "flake8>=4.0.1",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Quality Assurance",
    ],
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "backend-analyzer=backend_analyzer.cli:main",
        ],
    },
    keywords="django, analysis, backend, frontend, integration",
) 